### ISSUE TITLE
The playermodel doesnt raise the hand when typing

### ISSUE THREAD

**Issue by danylopez123** [BadgerCode/emojichat#47]
Normally, when you start to type, your playermodel makes an animation where the hand raises up, this addon will prevent them from doing that animation.

Why am i saying this? Because im using this addon of Chat Bubbles: https://steamcommunity.com/sharedfiles/filedetails/?id=125976234 and because it doesn't do the animation or there must be something in this EmojiChat addon, it also prevents of showing the chat bubble from that addon.

**Comment by BadgerCode** [comment]
Hey.

I'll have a look into this now

**Comment by BadgerCode** [comment]
Yup. It seems like the addon you mentioned uses `ply:IsTyping()` which doesn't work with custom chatboxes.

I'll see if I can fix this functionality.

**Comment by BadgerCode** [comment]
I have created a fix for this in bd4dc3f and I will now release it.

**Comment by BadgerCode** [comment]
![Preview](https://i.imgur.com/3nK5oTT.gif)

**Comment by BadgerCode** [comment]
I have released the fix for this. Please let me know if you have any other problems!
